document.addEventListener("DOMContentLoaded",()=>{const n=document.querySelector(".video__box");if(!n)return;const e=n.querySelector(".video__item"),i=n.querySelector(".nav-video"),y=document.querySelectorAll(".video-youtube__iframe"),l=n.querySelector(".nav-video__btn-fullscreen"),d=l?.querySelector("img"),u=n.querySelector(".nav-video__btn-play"),c=n.querySelector(".nav-video__btn-pause"),_=n.querySelector(".nav-video__btn-mute"),p=_?.querySelector("img");let v;e.muted=!0,c&&(c.style.display="none");function r(t){t&&(t.tagName==="VIDEO"?t.paused||t.pause():t.tagName==="IFRAME"&&t.contentWindow&&t.contentWindow.postMessage(JSON.stringify({event:"command",func:"pauseVideo"}),"*"))}function m(){y.forEach(t=>r(t))}function E(){r(e),s()}function a(){clearTimeout(v),i?.classList.remove("hidden"),!e.paused&&document.fullscreenElement===n&&(v=setTimeout(()=>i?.classList.add("hidden"),2e3))}function f(){!e.paused&&document.fullscreenElement===n&&i?.classList.add("hidden")}function s(){!u||!c||(e.paused?(u.style.display="block",c.style.display="none",a()):(u.style.display="none",c.style.display="block"))}u?.addEventListener("click",()=>{m(),document.querySelectorAll(".video-course-program__item").forEach(t=>r(t)),e.play(),s(),a()}),c?.addEventListener("click",()=>{E(),a()}),e.addEventListener("play",()=>{m(),document.querySelectorAll(".video-course-program__item").forEach(t=>r(t)),s()}),e.addEventListener("pause",s),_?.addEventListener("click",()=>{e.muted=!e.muted,p&&(p.src=e.muted?"assets/img/icons/sound-off.svg":"assets/img/icons/sound-on.svg")}),n.addEventListener("mouseenter",a),n.addEventListener("mousemove",a),n.addEventListener("mouseleave",f),n.addEventListener("touchstart",()=>{i?.classList.contains("hidden")?a():e.paused||i?.classList.add("hidden")}),l?.addEventListener("click",()=>{document.fullscreenElement===n?document.exitFullscreen():n.requestFullscreen?.()}),document.addEventListener("fullscreenchange",()=>{document.fullscreenElement===n?(d&&(d.src="assets/img/icons/fullscreen-exit.svg"),e.style.objectFit="contain",v=setTimeout(()=>i?.classList.add("hidden"),2e3)):(d&&(d.src="assets/img/icons/fullscreen.svg"),e.style.objectFit="cover",i?.classList.remove("hidden"),clearTimeout(v))});const o=new IntersectionObserver(t=>{t.forEach(g=>{g.isIntersecting||r(g.target)})},{threshold:.25});o.observe(e),y.forEach(t=>o.observe(t))}),document.addEventListener("DOMContentLoaded",()=>{const n=document.querySelectorAll(".gallery__preview");if(!n.length)return;let e=0;const i=[...n].map(s=>s.src),y=5,l=document.createElement("div");l.className="gallery-viewer",l.innerHTML=`
		<div class="gallery-viewer__overlay"></div>

		<button class="gallery-viewer__close">
			<img src="/assets/img/icons/close.svg" alt="Close">
		</button>

		<div class="gallery-viewer__content">
			<img class="gallery-viewer__image" src="">
			<div class="gallery-viewer__controls">
				<button class="gallery-viewer__prev"><img src="/assets/img/icons/arrow-slider.svg" alt="Image"></button>
				<div class="gallery-viewer__dots"></div>
				<button class="gallery-viewer__next"><img src="/assets/img/icons/arrow-slider.svg" alt="Image"></button>
			</div>
		</div>
	`,document.body.append(l);const d=l.querySelector(".gallery-viewer__image"),u=l.querySelector(".gallery-viewer__prev"),c=l.querySelector(".gallery-viewer__next"),_=l.querySelector(".gallery-viewer__overlay"),p=l.querySelector(".gallery-viewer__close"),v=l.querySelector(".gallery-viewer__dots");l.style.display="none",i.forEach((s,o)=>{const t=document.createElement("span");t.className="gallery-dot",t.addEventListener("click",()=>{e=o,m()}),v.append(t)});const r=v.querySelectorAll(".gallery-dot");function m(){d.src=i[e];const s=r.length;let o=0,t=s;s>y&&(o=e-2,t=e+3,o<0&&(o=0,t=y),t>s&&(t=s,o=s-y)),r.forEach((g,L)=>{g.classList.remove("active"),L>=o&&L<t?g.style.display="block":g.style.display="none"}),r[e].classList.add("active"),u.classList.toggle("disabled",e===0),c.classList.toggle("disabled",e===i.length-1)}function E(s){e=s,m(),l.style.display="block",l.classList.add("active"),document.body.style.overflow="hidden"}function a(){l.classList.remove("active"),l.style.display="none",document.body.style.overflow=""}n.forEach((s,o)=>{s.addEventListener("click",()=>E(o))}),c.addEventListener("click",()=>{e>=i.length-1||(e++,m())}),u.addEventListener("click",()=>{e<=0||(e--,m())}),_.addEventListener("click",a),p.addEventListener("click",a);let f=0;d.addEventListener("touchstart",s=>{f=s.touches[0].clientX}),d.addEventListener("touchend",s=>{const o=s.changedTouches[0].clientX;f-o>50&&e<i.length-1&&c.click(),o-f>50&&e>0&&u.click()})});
