document.addEventListener("DOMContentLoaded",()=>{const o=document.querySelector(".video__box");if(!o)return;const t=o.querySelector(".video__item"),i=o.querySelector(".nav-video"),u=document.querySelectorAll(".video-youtube__iframe"),s=o.querySelector(".nav-video__btn-play"),c=o.querySelector(".nav-video__btn-pause"),v=o.querySelector(".nav-video__btn-mute"),y=v?.querySelector("img");let f;t.muted=!0,c.style.display="none";function a(e){e&&(e.tagName==="VIDEO"?e.paused||e.pause():e.tagName==="IFRAME"&&e.contentWindow&&e.contentWindow.postMessage(JSON.stringify({event:"command",func:"pauseVideo"}),"*"))}function g(){u.forEach(e=>a(e))}function _(){a(t),d()}function l(){clearTimeout(f),i.classList.remove("hidden"),t.paused||(f=setTimeout(()=>i.classList.add("hidden"),2e3))}function p(){t.paused||i.classList.add("hidden")}s.addEventListener("click",()=>{g(),document.querySelectorAll(".video-course-program__item").forEach(e=>a(e)),t.play(),d(),l()}),c.addEventListener("click",()=>{_(),l()}),t.addEventListener("play",()=>{g(),document.querySelectorAll(".video-course-program__item").forEach(e=>a(e)),d()}),t.addEventListener("pause",d);function d(){t.paused?(s.style.display="block",c.style.display="none",l()):(s.style.display="none",c.style.display="block")}v.addEventListener("click",()=>{t.muted=!t.muted,y&&(y.src=t.muted?"assets/img/icons/sound-off.svg":"assets/img/icons/sound-on.svg")}),o.addEventListener("mouseenter",l),o.addEventListener("mousemove",l),o.addEventListener("mouseleave",p),o.addEventListener("touchstart",()=>{i.classList.contains("hidden")?l():i.classList.add("hidden")});const m=new IntersectionObserver(e=>{e.forEach(n=>{n.isIntersecting||a(n.target)})},{threshold:.25});m.observe(t),u.forEach(e=>m.observe(e))}),document.addEventListener("DOMContentLoaded",()=>{const o=document.querySelectorAll(".gallery__preview");if(!o.length)return;let t=0;const i=[...o].map(e=>e.src),u=5,s=document.createElement("div");s.className="gallery-viewer",s.innerHTML=`
		<div class="gallery-viewer__overlay"></div>

		<button class="gallery-viewer__close">
			<img src="/assets/img/icons/close.svg" alt="Close">
		</button>

		<div class="gallery-viewer__content">
			<img class="gallery-viewer__image" src="">
			<div class="gallery-viewer__controls">
				<button class="gallery-viewer__prev"><img src="/assets/img/icons/arrow-slider.svg" alt="Image"></button>
				<div class="gallery-viewer__dots"></div>
				<button class="gallery-viewer__next"><img src="/assets/img/icons/arrow-slider.svg" alt="Image"></button>
			</div>
		</div>
	`,document.body.append(s);const c=s.querySelector(".gallery-viewer__image"),v=s.querySelector(".gallery-viewer__prev"),y=s.querySelector(".gallery-viewer__next"),f=s.querySelector(".gallery-viewer__overlay"),a=s.querySelector(".gallery-viewer__close"),g=s.querySelector(".gallery-viewer__dots");s.style.display="none",i.forEach((e,n)=>{const r=document.createElement("span");r.className="gallery-dot",r.addEventListener("click",()=>{t=n,l()}),g.append(r)});const _=g.querySelectorAll(".gallery-dot");function l(){c.src=i[t];const e=_.length;let n=0,r=e;e>u&&(n=t-2,r=t+3,n<0&&(n=0,r=u),r>e&&(r=e,n=e-u)),_.forEach((L,E)=>{L.classList.remove("active"),E>=n&&E<r?L.style.display="block":L.style.display="none"}),_[t].classList.add("active"),v.classList.toggle("disabled",t===0),y.classList.toggle("disabled",t===i.length-1)}function p(e){t=e,l(),s.style.display="block",s.classList.add("active"),document.body.style.overflow="hidden"}function d(){s.classList.remove("active"),s.style.display="none",document.body.style.overflow=""}o.forEach((e,n)=>{e.addEventListener("click",()=>p(n))}),y.addEventListener("click",()=>{t>=i.length-1||(t++,l())}),v.addEventListener("click",()=>{t<=0||(t--,l())}),f.addEventListener("click",d),a.addEventListener("click",d);let m=0;c.addEventListener("touchstart",e=>{m=e.touches[0].clientX}),c.addEventListener("touchend",e=>{const n=e.changedTouches[0].clientX;m-n>50&&t<i.length-1&&y.click(),n-m>50&&t>0&&v.click()})});
